### ISSUE TITLE
FAQ documentation: To delete the last sentence

### ISSUE THREAD

**Issue by Chardonneaur** [openmost/AskYourDatabase#1]
Hi Ronan,

This last part of the documentation:
"What does this plugin do?
It allows you to generate a OpenAPI standard documentation for Matomo API based on your configuration."
can be removed.
You can substitute it by:
"How to use this plugin?"
"To use this plugin, please visit [AskYourDatabase](https://www.askyourdatabase.com/) and create an account. You will receive your credentials upon registration."

**Comment by ronan-hello** [comment]
Hi @Chardonneaur,

Thank you for your issue, this is fixed now.
